Extending rvsteel-api to rvsteel-soc
riscv-steel/riscv-steel pull request #32
Opened 2024-01-28 21:29 UTC by AlexxMarkov

Added functionality for working with uart, timer.
Wrote up the memory card in rvsteel-soc.h and more.

I'm sorry, but I seem to have made changes that greatly affect the change documentation section. But I think adding this functionality will set a strategy for expanding the source code.

But I haven’t checked how it works :) I hope for you, until I added a simulation for the SoC in Verilator.

2024-01-29 09:15 UTC, rafaelcalcada commented
I'll try running the new code on Arty. All looks good. Do you have an FPGA board? Sometimes I do a basic check just by running the new code.

2024-01-29 16:51 UTC, AlexxMarkov commented
Well, it looks like I fixed what I planned :)

2024-01-29 20:11 UTC, rafaelcalcada commented
Cool, a guy from Brazil made a pull request a few months ago adding a version of the demo project for a Tang Nano 20k, it would be nice to have the demo project ported to the 9k variant also ;)

2024-01-30 19:26 UTC, rafaelcalcada commented
I just brought the latest changes in main to this branch. I'll try running on the FPGA now.

2024-01-30 21:27 UTC, rafaelcalcada requested changes
Hi Alex! The changes look nice. I wrote a code review with some remarks.

I could compile and run the minimal Hello World example (`main.c`), but trying to compile the software for the demo projects fails because there are missing definitions in `rvsteel_soc.h` - `busy_wait` and `uart_read_last_char`.

2024-01-30 21:27 UTC, rafaelcalcada commented on software/api/rvsteel_csr.h
> +typedef uint32_t csr32_t;
`xlen_t` will always be 32 bits, so there is no need to define a `xlen_t` type - we can make it `uint32_t`. Same with `csr32_t`, all CSRs in Steel are 32 bits wide.

2024-01-31 06:22 UTC, AlexxMarkov commented on software/api/rvsteel_uart.h
> +__STATIC_INLINE void uart_send_char(UART_TypeDef *UARTx, const char c)
What do you mean by default?
I can do something like this:
```c
#define UART0_SEND_CHAR(c) uart_send_char(UART0, c)
```

2024-01-31 06:24 UTC, AlexxMarkov commented on software/api/rvsteel_uart.h
> +// Machine Timer Registers
Yes, sorry, I didn't notice.

2024-01-31 06:28 UTC, AlexxMarkov commented on software/api/rvsteel_uart.h
> +} UART_TypeDef;
You are right. I think I can fix this:

```c
typedef struct
{
  volatile uint32_t TX;
  volatile uint32_t RX;
} UartDevice;
```

2024-01-31 06:29 UTC, AlexxMarkov commented on software/template_project/main.c
> +  while (1)
I will return `busy_wait()`

2024-01-31 06:33 UTC, AlexxMarkov commented on software/api/rvsteel_gcc.h
> +// ----------------------------------------------------------------------------
I'll remove this in the next commit:

```c
#define __I
#define __O
#define __IO
#define __INLINE
#define __STATIC_INLINE
```

2024-01-31 06:35 UTC, AlexxMarkov commented on software/api/rvsteel_csr.h
> +#if __riscv_xlen == 32
OK. I'll replace it with `"Unsupported XLEN"` and change everything to `uint32_t`

2024-01-31 19:35 UTC, rafaelcalcada commented on software/api/rvsteel_uart.h
> +__STATIC_INLINE void uart_send_char(UART_TypeDef *UARTx, const char c)
I was thinking about something like C++, for example `void uart_send_char(const char c, UartDevice* uart = UART0)`. But I just found out it doesn't work in C. We will need to update the major version. I don't think it is a big problem now, few people are using the API. But before making this change in the API I think the user needs to have the ability to have multiple UARTs, otherwise we will change the API and its version for a feature not yet present.

2024-01-31 19:36 UTC, rafaelcalcada approved these changes

2024-01-31 19:51 UTC, AlexxMarkov commented
I returned the old api as it was before in rvseel-api. That's probably why everything is fine. But I also left a new API in case it is needed. If this is unnecessary functionality, then I think you can close this pull request.

2024-01-31 20:12 UTC, AlexxMarkov commented
I still doubt how correctly I placed the `static inline` functions in the header files `rvsteel_mtimer.h, rvsteel_uart.h`. Maybe it would be better to move them to some `plib or hal`. Leaving only the structure with registers.

2024-01-31 20:12 UTC, merged

2024-02-01 13:41 UTC, AlexxMarkov commented
Hello @rafaelcalcada, I'll probably leave it as it is for now. I won't split it into `plib or hal`.