Add SPI controller: 4 modes, adjustable speed
riscv-steel/riscv-steel pull request #55
Opened 2024-02-24 23:30 UTC by rafaelcalcada

Hi @AlexxMarkov, it took me quite some time but it's finally here, the SPI controller. It can operate in the 4 modes, the speed can be adjusted (base clock speed can be divided by 2 up to 512) and the number of chip select lines can also be configured.

I didn't write docs yet, but I will. My plan is making the v1.3 release with the latest new features: mtimer, GPIO and SPI. But before making the release I need to write docs for everything that is going to be added and this is going to take a week or a bit more.

2024-02-25 18:53 UTC, AlexxMarkov commented
Additionally, I would like to add that perhaps I was wrong when I started using `cocotb` to write tests in `Python` here. I wanted to simplify and systematize the approach to writing tests using open source tools, but it seems that this idea was not the most successful(

2024-02-25 18:57 UTC, AlexxMarkov requested changes

2024-02-25 18:57 UTC, AlexxMarkov commented on hardware/spi/rvsteel_spi.v
> +  assign pico = curr_state == SPI_READY ? 1'bZ : pico_tristate;
It is not entirely clear how much high-impedance state should be used. Usually Master SPI has `Push-pull` on its lines and Slave switches `MISO` output from/to high-impedance state.

2024-02-25 23:41 UTC, rafaelcalcada commented on hardware/spi/rvsteel_spi.v
> +    else if (rw_address == 32'h80030000 && write_request == 1'b1 && |write_strobe == 1'b1 && write_data[31:1] == 31'b0)
For example, if the user writes 3 instead of 1, then CPOL will hold 1 and not 3. This is a way to enforce only legal values get written: either 0 or 1.

2024-02-25 23:42 UTC, rafaelcalcada commented on hardware/spi/rvsteel_spi.v
> +    else if (rw_address == 32'h80030000 && read_request == 1'b1)
I'll update the SPI and the UART, the full addresses are hardcoded in these modules, making it not possible to relocate them to another memory region.

2024-02-25 23:48 UTC, rafaelcalcada commented on hardware/spi/rvsteel_spi.v
> +    else if (rw_address == 32'h80030010 && write_request == 1'b1 && |write_strobe == 1'b1 && write_data[31:8] == 8'b0) begin
Ok, I'll make them 32-bit.

2024-02-25 23:51 UTC, rafaelcalcada commented on hardware/spi/rvsteel_spi.v
> +  assign pico = curr_state == SPI_READY ? 1'bZ : pico_tristate;
Indeed `pico` does not need to be high-impedance when not transmitting. I'll remove this tri-state.

2024-02-25 23:57 UTC, rafaelcalcada commented on hardware/spi/rvsteel_spi.v
> +  always @(posedge clk_edge) begin
The controller has a busy bit that can be read on address 0x18. It is only safe to read a value when the busy bit is 0. It indicates the transfer has finished. If you read while the SPI is busy at sending/receiving you will definetely get undefined results. This is not a problem, the SPI clock can and most likely needs to be slower than the system clock, depending on the peripherals.

2024-02-26 05:11 UTC, AlexxMarkov commented on hardware/spi/rvsteel_spi.v
> +  always @(posedge clk_edge) begin
Yes, you are right. I'm sorry, I didn't take that into account.

2024-02-26 05:30 UTC, AlexxMarkov commented on hardware/spi/rvsteel_spi.v
> +    else if (rw_address == 32'h80030000 && write_request == 1'b1 && |write_strobe == 1'b1 && write_data[31:1] == 31'b0)
My point was that any values in the [31:1] range will not change the behavior. Maybe I'll be wrong. But I think this is an unnecessary waste of resources. It may be enough to write in the documentation about record availability only 0 or 1, without additional protection in RTL.

2024-02-26 21:35 UTC, merged